---

#Install the base software
- name: "Install_software"
  become: "yes"
  yum:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{
    satellite_deployment_packages[satellite_deployment_version | string] +
    satellite_deployment_extra_packages + satellite_deployment_plugin_packages
    }}"
  tags:
    - "install"
    - "update_satellite"
    - "skip_ansible_lint" # ANSIBLE0010
