---
- name: "Set network interface IP"
  shell: "nmcli con mod {{ satellite_deployment_net_interface }}
    ipv4.addresses '{{ satellite_deployment_ip_address }}/{{
    satellite_deployment_net_prefix }}'"
  tags:
    - "set_network"

- name: "Set network interface GW"
  shell: "nmcli con mod {{ satellite_deployment_net_interface }} ipv4.gateway
    {{ satellite_deployment_gw_address }}"
  tags:
    - "set_network"

- name: "Set network interface method manual"
  shell: "nmcli con mod {{ satellite_deployment_net_interface }} ipv4.method
    manual"
  tags:
    - "set_network"

- name: "Set network interface autoconnect"
  shell: "nmcli con mod {{ satellite_deployment_net_interface }}
    connection.autoconnect yes"
  tags:
    - "set_network"

- name: "Set network interface UP"
  shell: "nmcli con up {{ satellite_deployment_net_interface }}"
  tags:
    - "set_network"
