---
- name: SATELLITE | upload_manifest | Copy mainfiest file to Satellite server
  copy:
    src: "satellite_manifest.zip"
    dest: /root/satellite_manifest.zip
    mode: 0644
    owner: root
    group: root

- name: SATELLITE | upload_manifest | Upload manifest to Satellite server
  command: /usr/bin/hammer --password "{{ vault_sat_admin_pwd }}" subscription upload --organization "{{ sat_org }}"  --file /root/satellite_manifest.zip --repository-url "{{ upstream_cdn_path }}"
