---
- hosts: satellite-server
  become: True
  tasks:
    - name: import_role for ansible-role-redhat_satellite6_installation 
      import_role: 
        name: ../../ansible-role-redhat_satellite6_installation

  vars_files:
    - "{{ satellite_deployment_vars }}"
